version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: 'docker-todo-client'
    ports:
      - '3000:3000'
    depends_on:
      - server
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: 'docker-todo-server'
    environment:
      MYSQL_HOST: docker-todo-mysql
    ports:
      - '3001:3001'
    restart: always
    depends_on:
      - db
  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    image: mysql
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TWzjy-19950825!?
      MYSQL_DATABASE: todoList
    container_name: 'docker-todo-mysql'
    volumes:
      - ../dataBase/mysql/log:/var/log/mysql
      - ../dataBase/mysql/data:/var/lib/mysql
      - ../dataBase/mysql/conf:/etc/mysql/conf.d